name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up dependencies
        uses: ./.github/actions/setup
      - name: Build affected projects
        run: npx nx affected -t build

  format:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up dependencies
        uses: ./.github/actions/setup
      - name: Run Prettier format check for affected files
        run: npx nx format:check

  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up dependencies
        uses: ./.github/actions/setup
      - name: Run ESLint for affected projects
        run: npx nx affected -t lint

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up dependencies
        uses: ./.github/actions/setup
      - name: Run Vitest tests for affected projects
        run: npx nx affected -t test

  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up dependencies
        uses: ./.github/actions/setup
      - name: Install Playwright dependencies
        run: npx playwright install --with-deps
      - name: Initialize database
        run: npx nx run db:setup:ci
      - name: Run E2E Cypress and Playwright tests
        run: npx nx affected -t e2e

  codegen:
    name: Code generation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up dependencies
        uses: ./.github/actions/setup
      - name: Generate PostgreSQL types
        run: npx nx run db:codegen
      - name: Generate GraphQL types
        run: npm run codegen:gql
      - name: Check generated files are unchanged
        run: |
          if [ "$(git diff --ignore-space-at-eol --text | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after running codegen script. See status below:"
            git diff --ignore-space-at-eol --text
            exit 1
          fi
